### ISSUE TITLE
Network无数据，Retrofit

### ISSUE THREAD

**Issue by loe15919252** [whataa/pandora#13]
项目用的是Retrofit2.3.0，底层是Okhttp3.8.0。但是然后没有数据。不知道什么原因呢？

**Comment by whataa** [comment]
有两个需要注意的地方：
1. 确保Pandora的拦截器作为OKHttp的最后一个拦截器被添加进去；
2. 打开页面右上角的开关；

如果步骤正确还是没数据，能否引入源码断点调试下，具体类为 `tech.linjiang.pandora.network.OkHttpInterceptor.java`

**Comment by whataa** [comment]
Close because of no response
