### ISSUE TITLE
调用open之后，没有看到pandora的界面弹出啊

### ISSUE THREAD

**Issue by Mignet** [whataa/pandora#14]
是不是和层级有什么关系？

**Comment by whataa** [comment]
需要悬浮窗权限才能显示，由于每个手机厂商的权限管理不同，无法统一判断是否有权限以及申请，所以请检查下。

**Comment by Mignet** [comment]
我打开了手机的悬浮窗权限，还是没有看到。。。是锤子手机

**Comment by Mignet** [comment]
桌面悬浮窗

**Comment by whataa** [comment]
请问使用Pandora的demo，点击中间的open按钮有反应吗？

我让朋友用他的锤子T2，Android6.0手机试了demo，根据截图来看是可以正常弹出权限申请提示窗并且显示Pandora功能面板的。由于我手中没有相应手机，所以还是麻烦你再按照流程试一下：
1. 在Application的onCreate中调用`Pandora.init(this).open()` ;
2. 打开应用，此时应该会提示授权悬浮窗，如果没有，到你的“设置-锁屏和安全-应用程序权限管理-首页悬浮窗”，找到App，点击打开；
3. 完成第二步后，杀掉app进程，重新打开。

如果顺利，完成第3步就应该能看到功能面板了。

**Comment by whataa** [comment]
Close because of no response
