### ISSUE TITLE
无法查看数据库

### ISSUE THREAD

**Issue by RichyXin** [whataa/pandora#16]
使用感不错,感谢作者
不过,我始终不能查看数据库文件
我的应用中数据库文件为 `/data/user/0/com.huaqin.deskclock/databases/alarm.db`
不能直接查看

**Comment by whataa** [comment]
1. 没有列出所有数据库列表；
2. 没有列出某个数据库的所有table；
3. 无法打开某个table；
4. CRASH 或 ANR；
5. 页面为空；

请问具体表现是以上的哪种情况，如果可以的话，可以发一下你创建数据库和表的SQL语句吗

**Comment by RichyXin** [comment]
是没有列出所有的数据库列表
我的手机是Android7.1.1的系统,
使用的是继承自SQLiteOpenHelper的方式创建数据库,不过我在新建数据库的时候使用的是ProtectStorage
具体如下:
```java
 @Override
    @TargetApi(Build.VERSION_CODES.N)
    public boolean onCreate() {
        final Context context = getContext();
        final Context storageContext;
        if (true) { //for N
            storageContext = context.createDeviceProtectedStorageContext();
            if (!storageContext.moveDatabaseFrom(context, ClockDatabaseHelper.DATABASE_NAME)) {
                ALog.e("Failed to migrate database: %s", ClockDatabaseHelper.DATABASE_NAME);
            }
        } else {
            storageContext = context;
        }

        mOpenHelper = new ClockDatabaseHelper(storageContext);
        return true;
    }
```

使用DeviceProtectedStorageContext新建的数据库也好,Sharepreference的xml文件也好,都不能显示出列表

**Comment by whataa** [comment]
谢谢反馈，当时并没有考虑到这快儿，现在已在v1.0.5添加了对device encrypted storage 的支持，可以查看对应的DB和SP了
