### ISSUE TITLE
Can not View the .db file located in the custom path

### ISSUE THREAD

**Issue by song314** [whataa/pandora#19]
It's a great Pandora ,but only not support ROOM

**Comment by song314** [comment]
the follow CMD can list the db file:
adb shell dumpsys meminfo yourpackagename

by the way, my db is save in the path like "sdcard/**/**.db" , not in the inner path (data/data/yourpackagename/db/*.db)

**Comment by song314** [comment]
the issues list in #16 do not contains my issues,  there is 2 database file in my app, one is created by Sqilte, the other created by ROOM, all the file can be viewed but the db created by ROOM

**Comment by song314** [comment]
![4871532313543_ pic_hd](https://user-images.githubusercontent.com/5258363/43054539-a3327654-8e64-11e8-82a0-db278aabb9f7.jpg)

**Comment by whataa** [comment]
I see. Pandora only supports viewing the database located in the default path. I also considered support for the database located in the custom path, but it is hidden currently, I will open it in later versions.

**Comment by song314** [comment]
I've solve this issue , I’ll send the PR

**Comment by whataa** [comment]
OK

**Comment by whataa** [comment]
#20
