### ISSUE TITLE
什么原因呢

### ISSUE THREAD

**Issue by qxxlove** [whataa/pandora#23]
Error:(90, 13) Failed to resolve: com.github.whataa:pandora:1.1.1
<a href="openFile:G:/github/SpareTimeApp/app/build.gradle">Show in File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>
遇到这种情况怎么办？

**Comment by whataa** [comment]
1. 确保添加了仓库地址`maven { url 'https://jitpack.io' }`
2. 确保gradle sync时没有打开offline
3. 确保版本名书写正确：不要忘记 版本名开头有一个`v`的符号

另外，建议你使用最新版本：v1.1.3

**Comment by qxxlove** [comment]
感谢作者的疑难解惑，怪自己，没看见这个：“v”
