### ISSUE TITLE
新版本初始化问题

### ISSUE THREAD

**Issue by burgessjp** [whataa/pandora#25]
你好，这是一个非常棒的一个库。这个库最新版本是在 `PdFileProvider ` 里面去做初始化的，这样做现在会带来一个问题，如果我想在 `Application onCreate` 里面去调用 `get()` 方法去做一些初始化的相关配置就会出现问题。

**Comment by whataa** [comment]
`PdFileProvider` 初始化的时机是在`Application`的`attachBaseContext`的时候，早于`onCreate`，不知道你想初始化什么东西，或者初始化的时候发生了什么异常吗

**Comment by burgessjp** [comment]
你这里的这个做法确定是在Application 被创建之后才会执行的。

```
public class PdFileProvider extends FileProvider {
    @Override
    public boolean onCreate() {
        if (getContext() instanceof Application) {
            Pandora.init(((Application) getContext()));
        }
        return super.onCreate();
    }
}
```

**Comment by burgessjp** [comment]
我的问题。
