### ISSUE TITLE
Logo Design For Pandora

### ISSUE THREAD

**Issue by zularizal** [whataa/pandora#26]
Hi @whataa ,  I'm a graphic designer after I review your project, I'm interested in your project and  I want to create a unique and modern logo for your project. You can see the logo that I have designed in the previous projects. 

Best Regards,
Zularizal

**Comment by whataa** [comment]
Welcome, and please see #1 firstly.

**Comment by zularizal** [comment]
Okay,i'm designing it

**Comment by zularizal** [comment]
Hi @whataa , sorry for late, this is my design logo for your project. This logo is inspired by P, slashes, square brackets and squares. Then I combine them.
What do you think?

If you like it, what about icons, which do you like?

If something wants to be changed, let me know

![bitmap](https://user-images.githubusercontent.com/38547278/46182994-fc937400-c2f8-11e8-9d2d-34ab24cc72cb.png)

**Comment by whataa** [comment]
Thank you @zularizal , I very like them and plan to put the logotype at the beginning of the README and use the second icon as pandora's launch icon. 

If you agree, please make a pull-request or upload them somewhere to let me download.

**Comment by zularizal** [comment]
I have uploaded the logo to the drive.

https://drive.google.com/open?id=1OeujXL_9sgftvsgXlcJFPrB22_J9MJGw

And also I have sent a pull request to you, check #28

**Comment by whataa** [comment]
Thanks again and I have added you to the 「Thanks」 list in the README.

**Comment by zularizal** [comment]
Okay, you are welcome.
