### ISSUE TITLE
正式包想打开这个功能该怎么配置？

### ISSUE THREAD

**Issue by guozhiqiang123** [whataa/pandora#27]
如题

**Comment by whataa** [comment]
**非常不建议这样做，而且也不提供正常的api进行配置。**

如果你只是想测试下，可以直接按照以下方式依赖：
```
implementation 'com.github.whataa:pandora:${RELEASE}'
```

然后在application的onCreate方法中调用：
```
tech.linjiang.pandora.util.Config.setSHAKE_SWITCH(false);
```
最后自己实现一个触发方式（例如某个按钮点击）手动调用：
```
Pandora.get().open();
```

**Comment by guozhiqiang123** [comment]
谢谢！因为我们我们内部给领导演示的包有时候也是release的，出现bug的时候需要Pandora进行跟踪，所以有这个非正常的需求。再次感谢！

**Comment by whataa** [comment]
好的，其实这种需求可以在gradle文件中通过`flavor`来配置，以实现不同的 `XXXimplementation`，只要满足你最后真正的release包使用的是`no-op`就行了，具体的你可以搜一下

**Comment by guozhiqiang123** [comment]
嗯嗯 好的
