### ISSUE TITLE
在okhttp中添加 builder.addInterceptor(Pandora.get().getInterceptor())的问题

### ISSUE THREAD

**Issue by guozhiqiang123** [whataa/pandora#30]
我使用的是Retrofit，并且添加了标题上的拦截器，普通请求没有问题，但是如果是下载东西，就一定会OOM
![qq 20181016154839](https://user-images.githubusercontent.com/20378988/47000712-6c0fbd00-d15b-11e8-9e7d-c161c8480563.png)

同时我还使用了这个https://github.com/ihsanbal/LoggingInterceptor,但是单独使用这个的时候是没有问题的。

**Comment by whataa** [comment]
好的我看看

**Comment by whataa** [comment]
已修复，请使用v1.2.1版本试试
