### ISSUE TITLE
Is it possible to disable shake-to-open from the code?

### ISSUE THREAD

**Issue by adrianaisemberg** [whataa/pandora#32]
I want to include the interceptor in release builds but only allow opening it via a click of a button.
How can I disable the shake feature from code rather than from the settings?

**Comment by whataa** [comment]
You can add the following code snippet in the application's onCreate:
```
tech.linjiang.pandora.util.Config.setSHAKE_SWITCH(false);
```

**Comment by adrianaisemberg** [comment]
`MIND == "BLOWN!"`

Exactly what I needed! Thank you!
