### ISSUE TITLE
pandora-no-op中没有util包，所以release打包时会失败

### ISSUE THREAD

**Issue by JesseWo** [whataa/pandora#33]
```
tech.linjiang.pandora.util.Config.setSHAKE_SWITCH(false);
```

_Originally posted by @whataa in https://github.com/whataa/pandora/issues/32#issuecomment-434534494_

**Comment by whataa** [comment]
#32 的解决方案只针对有需求的少部分用户，不算一个公开API。
在此之前我设想的是默认开启“摇一摇打开”，因为只是在开发环境使用，所以不影响。
但是现在看来这个配置的需求还是挺大的。既然这样，那就把该配置作为一个正式API开放出来。

**Comment by whataa** [comment]
Pandora.get().disableShakeSwitch();
