### ISSUE TITLE
iOS开发照你的引入说明来报错了

### ISSUE THREAD

**Issue by songxing10000** [whataa/pandora#36]
![image](https://user-images.githubusercontent.com/10040131/50382756-875df200-06e1-11e9-9c15-cd45d393c9a4.png)

**Comment by songxing10000** [comment]
明天去公司 试试，多谢指点

**Comment by songxing10000** [comment]
因为项目 目前的现状是安卓先做了好几版了，所以，想利用你的工具在界面上，看能实现导出一些控件的颜色字号背景色之类的给iOS用不

**Comment by songxing10000** [comment]
已解决，本地环境问题，https://www.kancloud.cn/songxing10000/text/890379

**Comment by whataa** [comment]
颜色字号这些可以通过在页面选取指定的控件得到，但是单位可能和iOS用到的不一样；另外，没有导出功能

**Comment by songxing10000** [comment]
用了下很不错了，跟iOS的FlEX一样强悍

**Comment by songxing10000** [comment]
支持，强制跳转任意activity吗，比如可以拿到activity的属性，可以先给个输入框设置这些值 ，然后 点击进入，就进入到这个activity了

**Comment by whataa** [comment]
谢谢。当前没有这个跳转Activity的功能，我看看有没有好的实现方案。当然，也欢迎提PR

**Comment by whataa** [comment]
最新版本 v1.3.0 已实现

**Comment by songxing10000** [comment]
强悍
