### ISSUE TITLE
格式json建议

### ISSUE THREAD

**Issue by leeyun** [whataa/pandora#39]
现在改成webview来显示并未实现并未进行格式化只实现了换行，既然是webview了建议引入[参考json格式化开源站点](https://junbaor.github.io/json/index.html)   这样既美观工作量也没那么大

**Comment by whataa** [comment]
之前的实现方式有些简陋和BUG，所以换成了webview，但是原则还是一样的：保持可读性的前提下不额外增加第三方引入。如果完全按照你贴出的这个站点的特性来显示的话，导入的js相关文件换来的效果比不高。不知你需要的效果具体有哪些，方便列出来吗

**Comment by whataa** [comment]
前面提交修复了有时不能换行的BUG，增加了颜色，不支持搜索，你看下最新版是否可用。
我暂时先关闭该issue，如果你还有任何问题可以再打开
