### ISSUE TITLE
Unable to merge dex

### ISSUE THREAD

**Issue by TIME1992** [whataa/pandora#4]
When I run the problem,How to fix this problem:
Error:Execution failed for task ':test:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> com.android.builder.dexing.DexArchiveMergerException: Unable to merge dex
Thanks for your help!

**Comment by whataa** [comment]
信息太少，我无法给出正确原因，不过出现Merge failed的原因大部分情况是引入了相同库但是不同版本导致的，这里有可能是support包、或者OKHttp，所以我建议你尝试以下代码：
```
debugImplementation ('com.github.whataa:pandora:v1.0.1') {
        // add this
        transitive false
}
```

**Comment by whataa** [comment]
Close because of no response
