### ISSUE TITLE
上传大图报错

### ISSUE THREAD

**Issue by gavinxxxxxx** [whataa/pandora#46]
04-24 11:43:38.396 8047-8104/net.ronance.debug W/System.err:     at tech.linjiang.pandora.network.OkHttpInterceptor.updateContent(OkHttpInterceptor.java:164)
04-24 11:43:38.396 8047-8104/net.ronance.debug W/System.err:     at tech.linjiang.pandora.network.OkHttpInterceptor.intercept(OkHttpInterceptor.java:81)
04-24 11:43:38.396 8047-8104/net.ronance.debug W/System.err:     at retrofit2.OkHttpCall.execute(OkHttpCall.java:186)
04-24 11:43:38.422 8047-8047/net.ronance.debug W/subscribeE:  Invalid index 0, size is 0 

 public static Content query(long id) {
        return CacheDatabase.queryList(Content.class, BaseColumns._ID + " = " + String.valueOf(id), "limit 1").get(0);
    }  这里越界了

**Comment by whataa** [comment]
已修改，请使用v2.0.2版本，有问题请随时重新打开
