### ISSUE TITLE
添加依赖后会崩溃

### ISSUE THREAD

**Issue by xiecai1234** [whataa/pandora#51]
2019-05-05 18:17:08.308 30725-30725/com.mobile.wx E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.mobile.wx, PID: 30725
    Theme: themes:{default=, iconPack:com.gometheme.defaulttheme}
    java.lang.NullPointerException: Attempt to invoke virtual method 'void java.lang.reflect.AccessibleObject.setAccessible(boolean)' on a null object reference
        at com.mobile.wx.ui.MeHomeFragment.setIndicator(MeHomeFragment.java:228)

**Comment by whataa** [comment]
你好，贴出的日志里没有Pandora相关的错误代码？

**Comment by xiecai1234** [comment]
嗯。只在build.gradle里加了依赖，代码里没有调用。Activity里套一个fragment，fragment的onCreateView里执行如下代码。用最新的有问题，还原到之前的v1.2.2就没问题了。如下：
mViewPager.setAdapter(myHomeViewPagerAdapter);
        mTablayout.setTabMode(TabLayout.MODE_FIXED);
        mTablayout.setVisibility(View.VISIBLE);
        mTablayout.post(new Runnable() {
            @Override
            public void run() {
                setIndicator(mTablayout, 40, 40);
            }
        });

public void setIndicator(TabLayout tabs, int leftDip, int rightDip) {
        Class<?> tabLayout = tabs.getClass();
        Field tabStrip = null;
        try {
            tabStrip = tabLayout.getDeclaredField("mTabStrip");
        } catch (NoSuchFieldException e) {
            e.printStackTrace();
        }

        tabStrip.setAccessible(true);

**Comment by whataa** [comment]
v1.2.2使用的 `design` 库的版本是 `26.1.0`，我看了下其中的Tablayout类里面有你反射需要的`mTabStrip `字段，后面经过多次迭代，Pandora最新的版本引用的`design` 的版本已经提升到 `28.0.0` 了，对应的类中已经不包含该字段，所以你反射得到的对象是null。

你可以修改你使用TabLayout的方案 或者 通过transitive使用你自己的design版本：
```
    implementation ("com.github.whataa:pandora:v2.0.3") {
        exclude group: 'com.android.support', module: 'design'
    }
    implementation "com.android.support:design:26.1.0"
```

**Comment by xiecai1234** [comment]
给力！

**Comment by whataa** [comment]
#56
