### ISSUE TITLE
冲突问题

### ISSUE THREAD

**Issue by joker-fu** [whataa/pandora#54]
debugApi ('com.github.whataa:pandora:v2.0.4') {
        exclude group: 'com.android.support'
        exclude group: 'com.squareup.okhttp3'
    }
    releaseApi ('com.github.whataa:pandora-no-op:v2.0.3') {
        exclude group: 'com.android.support'
        exclude group: 'com.squareup.okhttp3'
    }

之前只需要排除support 今天升级2.0.4连okhttp也要排除了 建议想办法处理下 今天也推荐了给了个朋友使用 他也是因为报冲突 老项目又不敢轻易动之前的 最后放弃使用了

**Comment by whataa** [comment]
从v2.0.3开始，Pandora对OKHttp的依赖版本升级为了最新的3.14.0，具体可以看 [升级原因](https://github.com/whataa/pandora/issues/45) 和 [v2.0.3更新说明](https://github.com/whataa/pandora/releases/tag/v2.0.3)，不升级OKHttp依赖的话，依赖最新的OKHttp的项目就用不了Pandora。

所以我还是建议把你们项目的OKHttp依赖更新，只需要提升版本号即可。OKHttp保证了兼容性的，不然OKHttp每次发版，不可能让开发者每次都改一大堆代码吧。

**Comment by joker-fu** [comment]
保证依赖更新 这也是我经常做的，但是很老的项目里面有些问题根深蒂固，不敢轻易去动，这是其一。其二比我现在这公司，对接了一些其他公司的项目，他们也对接了很多其他公司，他们提供的arr也不会实时更新的，更新牵扯很大。还有这个项目有想建个群么？

**Comment by whataa** [comment]
按我的理解只有一个OKHttp的版本冲突问题，解决起来应该不至于你说的那么严重，按照同样的方式把其它library的OKHttp也给exclude，然后引入最新的版本，最后再看看运行有没有什么问题（仅个人见解）。群的话没有，如果你愿意的话，可以加我QQ 837979117 一起讨论。

**Comment by whataa** [comment]
#56
