### ISSUE TITLE
查看接口时 response_size = -1

### ISSUE THREAD

**Issue by ice45571** [whataa/pandora#55]
![-1](https://user-images.githubusercontent.com/21982940/57758529-77938880-772a-11e9-8da6-5844bd8f32d5.png)
![sc](https://user-images.githubusercontent.com/21982940/57758534-78c4b580-772a-11e9-92a7-f5632f4a0b35.png)

**Comment by ice45571** [comment]
因为项目不能升级compileSdk缘故 用的是1.3.0 有好的解决方法么

**Comment by whataa** [comment]
Pandora使用的`findViewById` 方法为 **非强转类型** 版本，需要compile-sdk至少为 `26`，所以对应的support-lib也需要至少为`26.1.0`，因此你可以按如下方式进行依赖（和 #51 相同）：

```
compileSdkVersion 26

implementation ("com.github.whataa:pandora:v2.0.3") {
    exclude group: 'com.android.support'
}
implementation "com.android.support:appcompat-v7:26.1.0"
implementation "com.android.support:recyclerview-v7:26.1.0"
implementation "com.android.support:design:26.1.0"
```

当然如果你引入了其它依赖库也间接依赖了不同版本的support包，你也需要自行 `exclude` 进行排除防止冲突。

另外，ResponseSize是直接读取的OKHttp的ResponseBody里的contentLength，我需要再看看有什么好的方案。

**Comment by ice45571** [comment]
谢谢！ 已解决。

**Comment by whataa** [comment]
#56
