### ISSUE TITLE
json格式建议

### ISSUE THREAD

**Issue by sher-loki** [whataa/pandora#57]
你好 在查看responseBody的时候 希望可以提供接口来格式化其中的值 因为如果需要解密的话就没办法了。暂时就只能退回低版本。

**Comment by whataa** [comment]
你好，我不太理解你的需求，你的意思是整个Response都是加了密的还是指json里的某个键对应的值是加了密的。另外，回退低版本的意思的以前的Pandora有方式满足你的需求吗？

**Comment by sher-loki** [comment]
你好 就是说我整个后台返回responseBody都是加过密的 在最新版本pandora查看就是乱码。
如果是老版本的话我就可以对其进行处理。但是老版本有okhttp的问题，我就直接clone了源码。
后来我想了一下 在查看responseBody的NetContentFragment中解密也挺好的，所以现在我的处理方式就是在NetContentFragment中的onPostExecute中将result通过接口传出去进行处理就好了。

**Comment by whataa** [comment]
我觉得你这个解密需求可以通过OKHttp的拦截器来实现，按照以下方式：
```
new OkHttpClient.Builder()
        ...
        .addInterceptor(Pandora.get().getInterceptor())
        .addInterceptor(你的解密拦截器)
        .build()
```
此时Pandora拿到的就是解密后的正常byte流

**Comment by sher-loki** [comment]
`  .addInterceptor(new Interceptor() {
                    @Override
                    public Response intercept(Chain chain) throws IOException {
                        Response originResponse = chain.proceed(chain.request());
                        ResponseBody originResponseBody = originResponse.body();
                        String content = originResponseBody.string();
                            Log.e("ApiManager", "intercept0" + content);
                        if (content.startsWith("{") && content.endsWith("}")) {//返回的是json数据就不解密
//                            HttpLoggingInterceptor.Logger.DEFAULT.log(FormatUtils.stringToJSON(str));
                            Log.e("ApiManager", "intercept1" + FormatUtils.stringToJSON(content));

                        } else {
                            try {
                                content = URLDecoder.decode(EncApi.getInstance().dec(content), "utf-8");
                                Log.e("ApiManager", "intercept2" + FormatUtils.stringToJSON(content));
//                                HttpLoggingInterceptor.Logger.DEFAULT.log(FormatUtils.stringToJSON(str));
                            } catch (Exception e) {
                                e.fillInStackTrace();
                            } finally {
                                originResponseBody.close();
                            }
                        }
                        return chain.proceed(chain.request())
                                .newBuilder()
                                .body(ResponseBody.create(originResponseBody.contentType(), content))
                                .build();
                    }
                })
                .addInterceptor(Pandora.get().getInterceptor())`
我一开始是这么写的intercepter 可是pandora拿到的还是解密前的。 所以我才会做之前那些操作。但是现在把pandora放在倒数第二个就可以了 不知道怎么回事。

**Comment by whataa** [comment]
因为拦截器是「递归」形式调用的，假如你添加的拦截器依次为ABC，那么请求发送和响应回来的调用顺序是 A->B->C ... C->B->A，所以得保证你的解密拦截器在Pandora的下层，就如B和C的关系，在网络结果回来时，B（pandora）拿到的就是C（解密）返回的正常流。

鉴于已经解决，我先关闭这个issue
