### ISSUE TITLE
目前发现小米3手机，安卓6.0 miui9 摇一摇没反应

### ISSUE THREAD

**Issue by luoqqsh** [whataa/pandora#6]
目前发现小米3手机，安卓6.0 miui9 摇一摇没反应，其他手机目前没发现

**Comment by whataa** [comment]
由于我手中没有对应机型和系统，所以希望你能在Pandora.sensorEventListener.onSensorChanged方法中添加日志并摇晃手机查看是否有输出，以确定到底是权限问题还是检测阈值不合理的问题

**Comment by xingstarx** [comment]
@luoqqsh 小米手机摇一摇没反应，估计是你没有开启悬浮窗权限吧

**Comment by whataa** [comment]
Close because of no response
