### ISSUE TITLE
貌似framelayout不能选择里面的元素

### ISSUE THREAD

**Issue by bravekingzhang** [whataa/pandora#63]
录制视频可以看这里。
https://github.com/bravekingzhang/pic_go/blob/master/ScreenRecord_Cut_20190621_160725.mp4

**Comment by bravekingzhang** [comment]
![image](https://user-images.githubusercontent.com/4476322/59908298-af839f00-943f-11e9-98ef-31ca3c716ce7.png)
猜测可能和这种诡异的写法有关，
但是使用UET 缺没有这个问题。

**Comment by whataa** [comment]
不是你代码诡异，是逻辑上不好处理，这种情况是存在的，UET的选择方式有一种”尝试“的意思，因为在同一个点击地方如果View都可见就有可能有多个符合条件的View，我使用的时候感觉有点突兀，就修改为了不再”尝试“，点击即选中，再点即取消，方便直观的理解，但是这样就可能导致没法选中想选的那个View，虽然这个View在视觉上是可见的，但是由于 ***层级关系和透明度以及背景色*** 等综合原因，代码逻辑上是无法命中它的。我当时也考虑了很久，感觉没法解决，因此我通过提供上图Parent-current-child的方式来提供另一个选择，虽然不是很直观。

解决方案可以长按住它把它移开，然后再重复操作直到选中你想的那个View。

**Comment by bravekingzhang** [comment]
好的，多谢
