### ISSUE TITLE
空指针问题

### ISSUE THREAD

**Issue by KaelInvoker** [whataa/pandora#67]
![image](https://user-images.githubusercontent.com/37531571/61711724-4e752100-ad87-11e9-875f-cd3d33a676e7.png)
如下代码会引起空指针

**Comment by KaelInvoker** [comment]
目前我是加了个非空判断。但我想问下addFunction在哪里添加比较合适呢？我考虑过加在闪屏页，那样我在debug目录下还得再额外加个闪屏页

**Comment by whataa** [comment]
原则上在onCreate及之后任何地方都可以加。
能否在上述位置打印下当前进程名看看是否是主进程，因为之前有个BUG是在其它进程调用出问题，我这边解决了后当时没有发新版本，现在我已经发布了，你可以试试`v2.0.5` 看看

**Comment by KaelInvoker** [comment]
好的。意思是说只有主进程才可以加这行代码是么？

**Comment by KaelInvoker** [comment]
嗯 改到2.0.5解决了

**Comment by whataa** [comment]
OK
