### ISSUE TITLE
ERROR: Failed to resolve: com.github.whataa:pandora-no-op:v2.0.5

### ISSUE THREAD

**Issue by mnayef95** [whataa/pandora#70]
```groovy
debugImplementation 'com.github.whataa:pandora:androidx_v2.0.5'
releaseImplementation 'com.github.whataa:pandora-no-op:v2.0.5'
```
When i add `'com.github.whataa:pandora:androidx_v2.0.5'` working fine but this `'com.github.whataa:pandora-no-op:v2.0.5'` unresolved, could you please provide the correct one for release implemenation?

```
ERROR: Failed to resolve: com.github.whataa:pandora-no-op:v2.0.5
```

**Comment by whataa** [comment]
the version of `pandora` and `pandora-no-op` are not always the same, and the latest version of `pandora-no-op` is v2.0.3 , you can find it in README and https://jitpack.io/#whataa/pandora-no-op.
