### ISSUE TITLE
Support proguard/R8 mapping.txt file in crash logs screen

### ISSUE THREAD

**Issue by mnayef95** [whataa/pandora#71]
If you enabled the proguard/R8 and there is a crash happened with QA team you will not be able to know what is the crash because the code is obfuscated so it's better if you adding integration with proguard/R8 mapping file

**Comment by whataa** [comment]
Hi, please check the latest version `v2.0.6 / androidx_v2.0.6` 

https://github.com/whataa/pandora/issues/43#issuecomment-482481469
