### ISSUE TITLE
该工具会导致Fuel网络请求框架无法正常网络请求

### ISSUE THREAD

**Issue by caiyoufei** [whataa/pandora#73]
使用版本：  
debugImplementation 'com.github.whataa:pandora:androidx_v2.0.6'
releaseImplementation 'com.github.whataa:pandora-no-op:v2.0.3'
使用的网络请求库：
https://github.com/kittinunf/fuel
异常：
No static field Companion of type Lokhttp3/internal/http/StatusLine$Companion; in class Lokhttp3/internal/http/StatusLine; or its superclasses (declaration of 'okhttp3.internal.http.StatusLine' appears in /data/app/com.abase.demo-1/base.apk:classes3.dex)
但是使用哆啦A梦的辅助工具是可以正常请求的：
https://github.com/didi/DoraemonKit/blob/master/Doc/android_cn_guide.md

**Comment by whataa** [comment]
#69  该相关问题都是由于OKHttp 版本不同造成，现已更新为与OKHttp版本无关。
