### ISSUE TITLE
期望加入的功能

### ISSUE THREAD

**Issue by zzyyppqq** [whataa/pandora#9]
position功能点击某个view的时候，可以显示是哪个Activity的View或者是哪个Activity下的Fragment的View  例如：MainActivity->HomeFragment->TextView->@app:id/tv_content
这样可以利用Android Studio的全局搜索功能快速定位到所要定位的页面及要修改view
应用页面太多了，会经常用到这个命令，查找Activity，如果应用本身就有这个功能就太好了
adb shell dumpsys window windows | grep -E 'mCurrentFocus|mFocusedApp' --color=always

**Comment by AndrewXiao** [comment]
当okhttp有个interceptor是负责加密request和解密response时，捕捉到的BODY是加密的内容，是否能够把.addInterceptor(Pandora.get().getInterceptor())中的OkHttpInterceptor开放出一个abstract方法来让开发人员自己解密内容？anyway，我先自己实现了。。

**Comment by AndrewXiao** [comment]
不好意思，我发现不改也可以搞定了，就是把Pandora Interceptor放在解密Interceptor之前添加就好了

**Comment by whataa** [comment]
「查看当前Activity的信息」已在最新的v1.1.0版本实现
